server:
    port: 8079    

#config:
#    oauth2:
#        clientID: confidential
#        clientSecret: secret
#        accessTokenUri: http://localhost:8081/oauth/token
#        userAuthorizationUri: http://localhost:8081/oauth/authorize
#        resourceURI: http://localhost:8082/api/

#security:
#    basic:
#        enabled: false


auth-server: http://192.168.0.174:9999/uaa
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
logging:
  level:
    org.springframework.security: DEBUG
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


